pub fn get_template(template: Option<String>) -> &'static [u8] {
    match template {
        None => b"# optional: runs automatically in zero-config mode\n# default = \"build\"\n\n[tasks.build]\nwatch = [\"src\"]\nrun = \"your command here\"\n",
        Some(x) => match x.to_lowercase().as_str() {
            "rust" => b"default = \"run\"\n[tasks.run]\nwatch = [\"src\"]\nextensions = [\"rs\"]\nrun = \"cargo run\"\n[tasks.test]\nwatch = [\"src\", \"tests\"]\nextensions = [\"rs\"]\nrun = \"cargo test\"\n[tasks.build]\nwatch = [\"src\"]\nextensions = [\"rs\"]\nrun = \"cargo build --release\"\n[tasks.check]\nwatch = [\"src\"]\nextensions = [\"rs\"]\nrun = \"cargo check\"\n[tasks.lint]\nwatch = [\"src\"]\nextensions = [\"rs\"]\nrun = \"cargo clippy\"",
            "node" | "nodejs" => b"default = \"dev\"\n[tasks.dev]\nwatch = [\"src\"]\nextensions = [\"js\", \"ts\"]\nrun = \"node index.js\"\n[tasks.test]\nwatch = [\"src\", \"tests\"]\nextensions = [\"js\", \"ts\"]\nrun = \"npm test\"\n[tasks.build]\nwatch = [\"src\"]\nextensions = [\"ts\"]\nrun = \"tsc\"\n[tasks.lint]\nwatch = [\"src\"]\nextensions = [\"js\", \"ts\"]\nrun = \"eslint src\"\n[tasks.format]\nwatch = [\"src\"]\nextensions = [\"js\", \"ts\"]\nrun = \"prettier --write src\"",
            "go" => b"default = \"run\"\n[tasks.run]\nwatch = [\".\"]\nextensions = [\"go\"]\nrun = \"go run .\"\n[tasks.test]\nwatch = [\".\"]\nextensions = [\"go\"]\nrun = \"go test ./...\"\n[tasks.build]\nwatch = [\".\"]\nextensions = [\"go\"]\nrun = \"go build -o app .\"\n[tasks.lint]\nwatch = [\".\"]\nextensions = [\"go\"]\nrun = \"golangci-lint run\"\n[tasks.fmt]\nwatch = [\".\"]\nextensions = [\"go\"]\nrun = \"gofmt -w .\"",
            "c" => b"default = \"build\"\n[tasks.build]\nwatch = [\"src\", \"include\"]\nextensions = [\"c\", \"h\"]\nrun = \"gcc src/*.c -Iinclude -o app\"\n[tasks.run]\nwatch = [\"src\", \"include\"]\nextensions = [\"c\", \"h\"]\nrun = \"make && ./app\"\n[tasks.clean]\nwatch = [\"src\"]\nextensions = [\"c\", \"h\"]\nrun = \"make clean\"",
            "cpp" => b"default = \"build\"\n[tasks.build]\nwatch = [\"src\", \"include\"]\nextensions = [\"cpp\", \"hpp\", \"h\"]\nrun = \"g++ src/*.cpp -Iinclude -o app\"\n[tasks.run]\nwatch = [\"src\", \"include\"]\nextensions = [\"cpp\", \"hpp\", \"h\"]\nrun = \"make && ./app\"\n[tasks.test]\nwatch = [\"src\", \"tests\"]\nextensions = [\"cpp\", \"hpp\"]\nrun = \"ctest --output-on-failure\"",
            "ruby" => b"default = \"run\"\n[tasks.run]\nwatch = [\".\"]\nextensions = [\"rb\"]\nrun = \"ruby main.rb\"\n[tasks.test]\nwatch = [\".\"]\nextensions = [\"rb\"]\nrun = \"bundle exec rspec\"\n[tasks.lint]\nwatch = [\".\"]\nextensions = [\"rb\"]\nrun = \"rubocop\"",
            "php" => b"default = \"run\"\n[tasks.run]\nwatch = [\".\"]\nextensions = [\"php\"]\nrun = \"php index.php\"\n[tasks.test]\nwatch = [\".\"]\nextensions = [\"php\"]\nrun = \"phpunit\"\n[tasks.lint]\nwatch = [\".\"]\nextensions = [\"php\"]\nrun = \"php -l index.php\"",
            "java" => b"default = \"build\"\n[tasks.build]\nwatch = [\"src\"]\nextensions = [\"java\"]\nrun = \"javac src/*.java -d out\"\n[tasks.run]\nwatch = [\"src\"]\nextensions = [\"java\"]\nrun = \"java -cp out Main\"\n[tasks.test]\nwatch = [\"src\", \"test\"]\nextensions = [\"java\"]\nrun = \"mvn test\"",
            "kotlin" => b"default = \"run\"\n[tasks.run]\nwatch = [\"src\"]\nextensions = [\"kt\"]\nrun = \"kotlinc src/*.kt -include-runtime -d app.jar && java -jar app.jar\"\n[tasks.test]\nwatch = [\"src\", \"test\"]\nextensions = [\"kt\"]\nrun = \"gradle test\"",
            "swift" => b"default = \"run\"\n[tasks.run]\nwatch = [\"Sources\"]\nextensions = [\"swift\"]\nrun = \"swift run\"\n[tasks.test]\nwatch = [\"Sources\", \"Tests\"]\nextensions = [\"swift\"]\nrun = \"swift test\"\n[tasks.build]\nwatch = [\"Sources\"]\nextensions = [\"swift\"]\nrun = \"swift build\"",
            "zig" => b"default = \"run\"\n[tasks.run]\nwatch = [\"src\"]\nextensions = [\"zig\"]\nrun = \"zig run src/main.zig\"\n[tasks.test]\nwatch = [\"src\"]\nextensions = [\"zig\"]\nrun = \"zig test src/main.zig\"\n[tasks.build]\nwatch = [\"src\"]\nextensions = [\"zig\"]\nrun = \"zig build\"",
            "elixir" => b"default = \"run\"\n[tasks.run]\nwatch = [\"lib\"]\nextensions = [\"ex\", \"exs\"]\nrun = \"mix run\"\n[tasks.test]\nwatch = [\"lib\", \"test\"]\nextensions = [\"ex\", \"exs\"]\nrun = \"mix test\"\n[tasks.compile]\nwatch = [\"lib\"]\nextensions = [\"ex\"]\nrun = \"mix compile\"",
            "haskell" => b"default = \"run\"\n[tasks.run]\nwatch = [\"src\"]\nextensions = [\"hs\"]\nrun = \"cabal run\"\n[tasks.test]\nwatch = [\"src\", \"test\"]\nextensions = [\"hs\"]\nrun = \"cabal test\"\n[tasks.build]\nwatch = [\"src\"]\nextensions = [\"hs\"]\nrun = \"cabal build\"",
            "css" | "scss" => b"default = \"build\"\n[tasks.build]\nwatch = [\"src\"]\nextensions = [\"scss\", \"sass\"]\nrun = \"sass src/main.scss dist/style.css\"\n[tasks.watch]\nwatch = [\"src\"]\nextensions = [\"css\", \"scss\"]\nrun = \"sass --watch src:dist\"",
            "lua" => b"default = \"run\"\n[tasks.run]\nwatch = [\".\"]\nextensions = [\"lua\"]\nrun = \"lua main.lua\"\n[tasks.test]\nwatch = [\".\"]\nextensions = [\"lua\"]\nrun = \"busted\"",
            "shell" | "sh" => b"default = \"run\"\n[tasks.run]\nwatch = [\".\"]\nextensions = [\"sh\"]\nrun = \"bash main.sh\"\n[tasks.lint]\nwatch = [\".\"]\nextensions = [\"sh\"]\nrun = \"shellcheck *.sh\"",
            _ => b"# optional: runs automatically in zero-config mode\n# default = \"build\"\n\n[tasks.build]\nwatch = [\"src\"]\nrun = \"your command here\"\n",
        },
    }
}
